runtime: python39  # or python311 if using Python 3.11

entrypoint: gunicorn -w 4 -b :$PORT app:app

instance_class: F2  # Choose an instance type based on traffic and performance

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  FIREBASE_API_KEY: "AIzaSyDOEhmnPgk5clxHn8dWR_oXx-Jv1aS_6BU"
  FIREBASE_PROJECT_ID: "f1-app-453903"

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
